#!/bin/bash
# Runs on host before devcontainer build to compute worktree paths
# Generates docker-compose.yml with the right mount configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_FOLDER="${LOCAL_WORKSPACE_FOLDER:-$(dirname "$SCRIPT_DIR")}"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

# Get the basename of the workspace (worktree name)
WORKTREE_NAME="$(basename "$WORKSPACE_FOLDER")"

# Determine the main repo path
# Check if this is a worktree by looking at .git
GIT_PATH="$WORKSPACE_FOLDER/.git"

if [ -f "$GIT_PATH" ]; then
    # This is a worktree - .git is a file pointing to the main repo
    # Format: gitdir: /path/to/main/.git/worktrees/<name>
    GITDIR=$(cat "$GIT_PATH" | sed 's/gitdir: //')
    # Go up 3 levels from .git/worktrees/<name> to get main repo path
    MAIN_PATH="$(cd "$GITDIR/../../.." && pwd)"
    IS_WORKTREE=true
elif [ -d "$GIT_PATH" ]; then
    # This is the main repo itself
    MAIN_PATH="$WORKSPACE_FOLDER"
    IS_WORKTREE=false
else
    echo "Error: Not a git repository: $WORKSPACE_FOLDER"
    exit 1
fi

# Ensure ~/.claude/treemux exists on host for bind mount
mkdir -p "$HOME/.claude/treemux"

# Generate docker-compose.yml based on worktree vs main
if [ "$IS_WORKTREE" = "true" ]; then
    # Worktree mode: mount worktree + readonly main + writable .git
    cat > "$COMPOSE_FILE" << EOF
# Auto-generated by init-devcontainer.sh - DO NOT EDIT
# Mode: worktree ($WORKTREE_NAME)

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        CLAUDE_CODE_VERSION: latest
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Worktree at /workspace/<name> with full read/write
      - $WORKSPACE_FOLDER:/workspace/$WORKTREE_NAME:rw,delegated
      # Main repo readonly
      - $MAIN_PATH:/workspace/main:ro
      # .git directory with full read/write (overlays the readonly mount)
      - $MAIN_PATH/.git:/workspace/main/.git:rw
      # Persistent volumes
      - claude-code-bashhistory:/commandhistory
      - claude-code-shared:/home/node/.claude-shared
      # Host bind for treemux plugin state
      - $HOME/.claude/treemux:/home/node/.claude/treemux:rw
    environment:
      HOST_TMUX_PANE: "${TMUX_PANE:-}"
      NODE_OPTIONS: "--max-old-space-size=4096"
      CLAUDE_CONFIG_DIR: /home/node/.claude
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"
      WORKTREE_NAME: $WORKTREE_NAME
    working_dir: /workspace/$WORKTREE_NAME
    user: node

volumes:
  claude-code-bashhistory:
  claude-code-shared:
EOF
    echo "Devcontainer initialized (worktree mode):"
    echo "  Worktree: $WORKTREE_NAME -> /workspace/$WORKTREE_NAME (read/write)"
    echo "  Main repo: $MAIN_PATH -> /workspace/main (readonly)"
    echo "  Main .git: $MAIN_PATH/.git -> /workspace/main/.git (read/write)"
else
    # Main repo mode: simple mount at /workspace/main
    cat > "$COMPOSE_FILE" << EOF
# Auto-generated by init-devcontainer.sh - DO NOT EDIT
# Mode: main repo

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        CLAUDE_CODE_VERSION: latest
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Main repo at /workspace/main with full read/write
      - $MAIN_PATH:/workspace/main:rw,delegated
      # Persistent volumes
      - claude-code-bashhistory:/commandhistory
      - claude-code-shared:/home/node/.claude-shared
      # Host bind for treemux plugin state
      - $HOME/.claude/treemux:/home/node/.claude/treemux:rw
    environment:
      HOST_TMUX_PANE: "${TMUX_PANE:-}"
      NODE_OPTIONS: "--max-old-space-size=4096"
      CLAUDE_CONFIG_DIR: /home/node/.claude
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"
      WORKTREE_NAME: main
    working_dir: /workspace/main
    user: node

volumes:
  claude-code-bashhistory:
  claude-code-shared:
EOF
    echo "Devcontainer initialized (main repo mode):"
    echo "  Main repo: $MAIN_PATH -> /workspace/main (read/write)"
fi
